### ISSUE TITLE
Fail to open bin file in Windows

### ISSUE THREAD

**Issue by z8a** [andrewpines/lpcisp#1]
Hi,
I've compiled the program with Code::Blocks and mingw32 and it works with .hex files but stat() function returns an error with .bin files. The error is "failed to open "xxx.bin" for reading: No error".

**Comment by andrewpines** [comment]
Hi,
  It should be fixed.  Please pull the latest version (0.2.1), build that, and see if it resolves your problem.  Thanks for your input and I hope you find lpcisp helpful.

     -Andrew
