### ISSUE TITLE
ISP code protection

### ISSUE THREAD

**Issue by z8a** [andrewpines/lpcisp#2]
Is it possible to protect code?

**Comment by andrewpines** [comment]
Yes, but that's handled by your hex or bin file.  LPC processors have a code read protect word (CRP) which determines what can and cannot be accessed.  It's usually a 32-bit value at 0x0000 02fc in your flash image.  Check the user manual for the part you're using for details.

You can set it in an assembly file like this:
	.org	0x02fc
	.word	0x87654321 

Be aware that you can brick your part if an invalid value is written to the CRP.

**Comment by z8a** [comment]
Thank you for your support. I'm not the original NXP application developer so I'm new to this. We are using Flash Magic to burn an LPC1765 but using your software can speed up programming because it works at an higher baud rate.
Your source were also useful because I've embedded it in a Silicon Labs BLE module to upgrade firmware via Bluetooth.
Many thanks.
